import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
const BannerPic = require('../public/pictures/6.jpg')

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.topBanner}>

          <div className={styles.havetWatch}>
            <h1 style={{ fontFamily: 'NewYorkTypeface' }}>Havet</h1>
            <h1 style={{ fontFamily: 'NewYorkTypeface' }}>Watches</h1>
            <p style={{ fontFamily: 'Gotham Pro' }}>Rose Gold White Mesh</p>
          </div>

        </div>

        <div className={styles.forWoman}>

        </div>

        <div className={styles.forMan}>

        </div>

      </div>

    </>
  )
}
